"""
Django settings for tev project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
GOOGLE_RECAPTCHA_SECRET_KEY = '6LfBfsgqAAAAAKsANK7ROm7OGslrc2e8KyIQsI_t'
# RECAPTCHA_PUBLIC_KEY = '6LfBfsgqAAAAAKsANK7ROm7OGslrc2e8KyIQsI_t'
# RECAPTCHA_PRIVATE_KEY = '6LfBfsgqAAAAAEEHpMdVD6ZyYU92kViCR3u-glX8'


RECAPTCHA_SECRET_KEY = '6LfEHykrAAAAABkw_UJlsjYAaa7x9SQV7vJemLF6'  # Captcha_Version3
RECAPTCHA_VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify'
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

SECRET_KEY = 'django-insecure-e&691z)oh*#_&yv(h^3sn^*=gxs09(%(5395)=xe+_im_bk^l&'
PSGC_TOKEN  = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2R4Y2xvdWQuZHN3ZC5nb3YucGgvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3Mzc3NzA3NjYsImV4cCI6MTgzMjM3ODc2NiwibmJmIjoxNzM3NzcwNzY2LCJqdGkiOiJyS1pNMm90NmJlaHFNaWtzIiwic3ViIjoyMTEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.q5MOfNtcQC-zcCg2kdsfZwf_gOm6Sw2QuiA5lDvfA6g"
PORTAL_TOKEN  = "Token 7a8203defd27f14ca23dacd19ed898dd3ff38ef6"
PORTAL_API_URL  = "https://caraga-portal.dswd.gov.ph/api/employee/list/load"
PSGC_PROVINCE_URL  = "https://dxcloud.dswd.gov.ph/api/psgc/provincesByRegion?region=160000000"
PSGC_CITY_URL  = "https://dxcloud.dswd.gov.ph/api/psgc/municipalityByProvince?province="
PSGC_BARANGAY_URL  = "https://dxcloud.dswd.gov.ph/api/psgc/barangayByMunicipality?municipality="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.humanize',
    'main',
    'receive',
    'tracking',
    'transaction',
    'libraries',
    'django_filters',
    'rest_framework',
    'channels',
    'django_recaptcha',
]





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
                'staticfiles': 'django.templatetags.static',
            }
        },
    },
]

WSGI_APPLICATION = 'tev.wsgi.application'
ASGI_APPLICATION = 'tev.asgi.application'

CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
}


DATABASES = {
    #for server to server
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tris',
        'USER': 'tris',
        'PASSWORD': 'vOHA]ko(5))If-LU',
        'HOST': '172.31.240.135',
        'PORT': '3306',
    },
    # #for server INFIMOS
    
    'finance': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'infimos_2023',
        'USER':'tris',
        'PASSWORD':'vOHA]ko(5))If-LU',
        'HOST':'172.31.240.235',
        'PORT':'3306',
    },

    'finance_2024': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'infimos_2024',
        'USER':'tris',
        'PASSWORD':'vOHA]ko(5))If-LU',
        'HOST':'172.31.240.235',
        'PORT':'3306',
    },

    'finance_2025': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'infimos_2025',
        'USER':'tris',
        'PASSWORD':'vOHA]ko(5))If-LU',
        'HOST':'172.31.240.235',
        'PORT':'3306',
    },

    'libraries_isps': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'libraries_isps',
        'USER':'tris',
        'PASSWORD':'vOHA]ko(5))If-LU',
        'HOST':'172.31.240.235',
        'PORT':'3306',
    },
    

    ##for server local but live database
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'tris',
    #     'USER': 'fmdDeveloper',
    #     'PASSWORD': 'M@tth3w6fmd-developer',
    #     'HOST': '172.31.240.235',
    #     'PORT': '3306',   
    # },
    # # for localhost main database
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'tev_db',
    #     'USER': 'root',
    #     'PASSWORD': '',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    # },
    # #for localhost INFIMOS database
    # 'finance': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'infimos_2023',
    #     'USER':'root',
    #     'PASSWORD':'qw1234',
    #     'HOST':'localhost',
    #     'PORT':'3307',
    # },
    # 'finance_2024': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'infimos_2024',
    #     'USER':'root',
    #     'PASSWORD':'qw1234',
    #     'HOST':'localhost',
    #     'PORT':'3307',
    # },
    # 'finance_2025': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'infimos_2025',
    #     'USER':'root',
    #     'PASSWORD':'qw1234',
    #     'HOST':'localhost',
    #     'PORT':'3307',
    # },

    # 'libraries_isps': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'libraries_isps',
    #     'USER':'root',
    #     'PASSWORD':'qw1234',
    #     'HOST':'localhost',
    #     'PORT':'3307',
    # },



    # 'finance': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'infimos_2023',
    #     'USER':'fmdDeveloper',
    #     'PASSWORD':'M@tth3w6fmd-developer',
    #     'HOST':'172.31.240.235',
    #     'PORT':'3306',
    # },
    # 'finance_2024': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'infimos_2024',
    #     'USER':'fmdDeveloper',
    #     'PASSWORD':'M@tth3w6fmd-developer',
    #     'HOST':'172.31.240.235',
    #     'PORT':'3306',
    # },

}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/staticfiles/'), ]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
