"""
Django settings for tev project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e&691z)oh*#_&yv(h^3sn^*=gxs09(%(5395)=xe+_im_bk^l&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.humanize',
    'main',
    'receive',
    'tracking',
    'transaction',
    'libraries',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
                'staticfiles': 'django.templatetags.static',
            }
        },
    },
]

WSGI_APPLICATION = 'tev.wsgi.application'
DATABASES = {
    ##for server to server
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tris',
        'USER': 'tris',
        'PASSWORD': 'vOHA]ko(5))If-LU',
        'HOST': '172.31.240.235',
        'PORT': '3306',
    },
    # #for server INFIMOS
    
    'finance': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'infimos_2023',
        'USER':'tris',
        'PASSWORD':'vOHA]ko(5))If-LU',
        'HOST':'172.31.240.235',
        'PORT':'3306',
    },

    'finance_2024': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'infimos_2024',
        'USER':'tris',
        'PASSWORD':'vOHA]ko(5))If-LU',
        'HOST':'172.31.240.235',
        'PORT':'3306',
    },

    ##for server local but live database
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'tris',
    #     'USER': 'fmdDeveloper',
    #     'PASSWORD': 'M@tth3w6fmd-developer',
    #     'HOST': '172.31.240.235',
    #     'PORT': '3306',
    # },
    # #for localhost main database
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'tev_db',
    #     'USER': 'root',
    #     'PASSWORD': '',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    # },
    # # #for localhost INFIMOS database
    # 'finance': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'finance',
    #     'USER':'root',
    #     'PASSWORD':'',
    #     'HOST':'localhost',
    #     'PORT':'3306',
    # },
    # 'finance_2024': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'infimos_2024',
    #     'USER':'root',
    #     'PASSWORD':'',
    #     'HOST':'localhost',
    #     'PORT':'3306',
    # },

    # 'finance': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'infimos_2023',
    #     'USER':'fmdDeveloper',
    #     'PASSWORD':'M@tth3w6fmd-developer',
    #     'HOST':'172.31.240.235',
    #     'PORT':'3306',
    # },
    # 'finance_2024': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'infimos_2024',
    #     'USER':'fmdDeveloper',
    #     'PASSWORD':'M@tth3w6fmd-developer',
    #     'HOST':'172.31.240.235',
    #     'PORT':'3306',
    # },

}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/staticfiles/'), ]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
