# Generated by Django 4.1 on 2024-02-20 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=50, null=True)),
            ],
            options={
                'db_table': 'charges',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cluster',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('acronym', models.CharField(blank=True, max_length=128, null=True)),
                ('chief', models.CharField(blank=True, max_length=128, null=True)),
                ('c_designation', models.CharField(blank=True, max_length=128, null=True)),
                ('approval', models.CharField(blank=True, max_length=128, null=True)),
                ('ap_designation', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=50, null=True)),
            ],
            options={
                'db_table': 'division',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RemarksLib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remarks_lib',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'role_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'system_configuration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TevOutgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_no', models.CharField(blank=True, max_length=128, null=True)),
                ('cluster', models.CharField(blank=True, max_length=128, null=True)),
                ('box_date_out', models.DateTimeField(auto_now_add=True, null=True)),
                ('box_b_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('box_b_out', models.DateTimeField(blank=True, null=True)),
                ('ard_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('ard_out', models.DateTimeField(blank=True, null=True)),
                ('otg_d_received', models.DateTimeField(blank=True, null=True)),
                ('otg_r_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('otg_d_forwarded', models.DateTimeField(blank=True, null=True)),
                ('otg_out_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('b_d_received', models.DateTimeField(blank=True, null=True)),
                ('b_r_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('b_d_forwarded', models.DateTimeField(blank=True, null=True)),
                ('b_out_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('j_d_received', models.DateTimeField(blank=True, null=True)),
                ('j_r_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('j_d_forwarded', models.DateTimeField(blank=True, null=True)),
                ('j_out_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('a_d_received', models.DateTimeField(blank=True, null=True)),
                ('a_r_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('a_d_forwarded', models.DateTimeField(blank=True, null=True)),
                ('a_out_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('out_by', models.CharField(blank=True, max_length=128, null=True)),
                ('is_print', models.BooleanField(default=False)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.division')),
                ('status', models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='main.status')),
            ],
            options={
                'db_table': 'tev_outgoing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TevIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('id_no', models.CharField(blank=True, max_length=128, null=True)),
                ('account_no', models.CharField(blank=True, max_length=128, null=True)),
                ('date_travel', models.CharField(blank=True, max_length=512, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('incoming_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('incoming_out', models.DateTimeField(blank=True, null=True)),
                ('slashed_out', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('is_upload', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.status')),
            ],
            options={
                'db_table': 'tev_incoming',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TevBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('charges', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.charges')),
                ('tev_incoming', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tevincoming')),
                ('tev_outgoing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tevoutgoing')),
            ],
            options={
                'db_table': 'tev_bridge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=128, null=True)),
                ('division', models.CharField(blank=True, max_length=128, null=True)),
                ('section', models.CharField(blank=True, max_length=128, null=True)),
                ('position', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.roledetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.authuser')),
            ],
            options={
                'db_table': 'staff_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.roledetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.authuser')),
            ],
            options={
                'db_table': 'role_permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Remarks_r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tevincoming')),
                ('remarks_lib', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.remarkslib')),
            ],
            options={
                'db_table': 'remarks_r',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayrolledCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('charges', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.charges')),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tevincoming')),
            ],
            options={
                'db_table': 'payrolled_charges',
                'managed': True,
            },
        ),
    ]
