# Generated by Django 4.0.2 on 2023-08-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='acronym',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
