# Generated by Django 4.0.2 on 2023-07-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevincoming',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True),
        ),
    ]
