# Generated by Django 4.1 on 2024-02-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevincoming',
            name='incoming_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
