# Generated by Django 4.0.2 on 2023-09-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='ap_designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='c_designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
