# Generated by Django 4.0.2 on 2023-08-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_division_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevincoming',
            name='account_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
