# Generated by Django 4.0.2 on 2023-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_division_ap_designation_division_c_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tevincoming',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='tevincoming',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tevincoming',
            name='middle_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
