# Generated by Django 4.1 on 2024-03-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_section_tevincoming_division_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tevincoming',
            old_name='division_id',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='tevincoming',
            old_name='section_id',
            new_name='section',
        ),
    ]
