# Generated by Django 4.1 on 2024-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tevincoming_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevincoming',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tevincoming',
            name='forwarded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tevincoming',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
