# Generated by Django 4.1 on 2024-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tevincoming_contact_no_tevincoming_forwarded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevincoming',
            name='date_reviewed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
