# Generated by Django 4.2.1 on 2024-03-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_systemconfiguration_date_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevincoming',
            name='date_payrolled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tevincoming',
            name='payrolled_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
