# Generated by Django 4.1 on 2024-04-22 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tevincoming_date_payrolled_tevincoming_payrolled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'transaction_logs',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tevincoming',
            name='is_latest',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
