# Generated by Django 4.1 on 2024-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_staffdetails_added_by_staffdetails_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tevincoming',
            name='is_latest',
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
