# Generated by Django 4.1 on 2024-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_created_by_chat_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.IntegerField(),
        ),
    ]
