# Generated by Django 4.1 on 2024-06-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_chat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
