# Generated by Django 4.2.16 on 2024-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevincoming',
            name='review_date_forwarded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tevincoming',
            name='review_forwarded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
