# Generated by Django 4.2.16 on 2024-10-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_tevincoming_review_date_forwarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarkslib',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
