# Generated by Django 4.2.16 on 2024-10-24 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remarkslib_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_from', models.DateField(blank=True, null=True)),
                ('d_to', models.CharField(blank=True, max_length=128, null=True)),
                ('d_still', models.CharField(blank=True, max_length=128, null=True)),
                ('departure', models.CharField(blank=True, max_length=128, null=True)),
                ('arrival', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'destination_time',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TravelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('means_of_transpo', models.CharField(blank=True, max_length=128, null=True)),
                ('transportation', models.CharField(blank=True, max_length=128, null=True)),
                ('per_diem', models.CharField(blank=True, max_length=128, null=True)),
                ('others', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('destination_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.destinationtime')),
            ],
            options={
                'db_table': 'travel_list',
                'managed': True,
            },
        ),
    ]
