# Generated by Django 4.2.16 on 2024-10-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_destinationtime_travellist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=128, null=True)),
                ('d_from', models.CharField(blank=True, max_length=128, null=True)),
                ('d_to', models.CharField(blank=True, max_length=128, null=True)),
                ('d_still', models.CharField(blank=True, max_length=128, null=True)),
                ('departure', models.CharField(blank=True, max_length=128, null=True)),
                ('arrival', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'destination_time',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='travellist',
            old_name='amount',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='travellist',
            old_name='means_of_transpo',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='travellist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='travellist',
            name='destination_time',
        ),
        migrations.RemoveField(
            model_name='travellist',
            name='others',
        ),
        migrations.RemoveField(
            model_name='travellist',
            name='per_diem',
        ),
        migrations.RemoveField(
            model_name='travellist',
            name='transportation',
        ),
        migrations.DeleteModel(
            name='DestinationTime',
        ),
    ]
