# Generated by Django 4.2.16 on 2024-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_traveldestination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travellist',
            old_name='municipality',
            new_name='municipalities',
        ),
        migrations.RenameField(
            model_name='travellist',
            old_name='province',
            new_name='provinces',
        ),
        migrations.AddField(
            model_name='travellist',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='traveldestination',
            table='travel_destination',
        ),
    ]
