# Generated by Django 4.0.10 on 2024-11-21 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_municipality_travellist_municipalities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=128, null=True)),
                ('province_acronym', models.CharField(blank=True, max_length=128, null=True)),
                ('municipality', models.CharField(blank=True, max_length=128, null=True)),
                ('barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('purok', models.CharField(blank=True, max_length=255, null=True)),
                ('means_of_transpo', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_fare', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('hire_rate', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('estimated_duration_of_travel', models.CharField(blank=True, max_length=128, null=True)),
                ('justification', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'fare_matrix',
                'managed': True,
            },
        ),
    ]
