# Generated by Django 4.0.10 on 2024-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_farematrix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farematrix',
            old_name='hire_rate',
            new_name='hire_rate_one_way',
        ),
        migrations.RenameField(
            model_name='farematrix',
            old_name='rate',
            new_name='rate_regular_fare',
        ),
        migrations.AddField(
            model_name='farematrix',
            name='hire_rate_whole_day',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True),
        ),
    ]
