# Generated by Django 4.0.10 on 2024-11-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_hire_rate_farematrix_hire_rate_one_way_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farematrix',
            name='regular_fare',
        ),
        migrations.AddField(
            model_name='farematrix',
            name='brgy_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='farematrix',
            name='city_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='farematrix',
            name='prov_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
