# Generated by Django 4.0.10 on 2024-11-27 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_farematrix_regular_fare_farematrix_brgy_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeansofTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'lib_means_of_transportation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='farematrix',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='farematrix',
            name='updated_by',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='farematrix',
            name='created_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
