# Generated by Django 4.0.10 on 2024-11-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_meansoftransportation_farematrix_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farematrix',
            name='means_of_transpo',
        ),
        migrations.AddField(
            model_name='farematrix',
            name='means_of_transportation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.meansoftransportation'),
            preserve_default=False,
        ),
    ]
