# Generated by Django 4.0.10 on 2024-11-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_farematrix_means_of_transpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farematrix',
            name='means_of_transportation',
        ),
        migrations.AddField(
            model_name='farematrix',
            name='means_of_transportation_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
