# Generated by Django 4.0.10 on 2024-11-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_farematrix_means_of_transportation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farematrix',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meansoftransportation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
