# Generated by Django 4.0.10 on 2024-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_farematrix_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farematrix',
            name='updated_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
