# Generated by Django 4.0.10 on 2024-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_farematrix_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meansoftransportation',
            name='updated_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
