# Generated by Django 4.0.10 on 2025-01-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_meansoftransportation_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibBarangays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_brgy', models.IntegerField()),
                ('brgy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('psgc_mun', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lib_barangays',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibMunicipalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_mun', models.IntegerField()),
                ('mun_name', models.CharField(blank=True, max_length=255, null=True)),
                ('psgc_province', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lib_municipalities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibProvinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_province', models.IntegerField()),
                ('prov_name', models.CharField(blank=True, max_length=255, null=True)),
                ('psgc_region', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lib_provinces',
                'managed': True,
            },
        ),
    ]
