# Generated by Django 4.2.18 on 2025-03-04 10:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_libbarangays_libmunicipalities_libprovinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farematrix',
            name='hire_rate_one_way',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='farematrix',
            name='hire_rate_whole_day',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='farematrix',
            name='rate_regular_fare',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=50, null=True),
        ),
    ]
