# Generated by Django 4.2.20 on 2025-05-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_libprojectsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='is_travel_expire',
            field=models.BooleanField(default=False),
        ),
    ]
