# Generated by Django 4.2.20 on 2025-05-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_systemconfiguration_days_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='section_head',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='sh_designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
