# Generated by Django 4.2.20 on 2025-06-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_division_section_head_division_sh_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='division_lbl',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
